new yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,21 +5,26 @@ branches:
 
 language: python
 
-install:
-    - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
-    - sudo dpkg -i hugo*.deb
-    - pip install Pygments
+# Install the apt prerequisites
+addons:
+  apt:
+    packages:
+      - python-pygments
 
+# Clean and don't fail
+install:
+  - rm -rf public || exit 0
+
+# Build the website
 script:
-    - hugo
-#
-after_success: |
-    if [ -n "$GITHUB_API_KEY_TRAVIS_SPECIAL" ]; then
-    git checkout --orphan master
-    git rm -rf --cached .
-    mv public/* .
-    rm -rf public hugo_*
-    git add -f --ignore-errors --all
-    git -c user.name='travis' -c user.email='travis' commit -m init
-    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY_TRAVIS_SPECIAL@github.com/$TRAVIS_REPO_SLUG master
-    fi
+  - cd src
+  - ../binaries/hugo --theme=hugo-theme-learn
+
+# Deploy to GitHub pages
+deploy:
+  provider: pages
+  skip_cleanup: true
+  local_dir: public
+  github_token: $GITHUB_API_KEY_TRAVIS_SPECIAL # Set in travis-ci.org dashboard
+  on:
+    branch: master
